A few tweaks to some tools that may be helpful for quick tests of functionality. Functionality is not complete compared to the client lib based tools, but does offer some degree of independence for verification of operations.

diff --git a/d1create b/d1create
--- a/d1create
+++ b/d1create
@@ -1,8 +1,6 @@
 #!/bin/bash
 # Creates content on a DataONE member node.
 #
-# Arguments: -c Certificate -i Identifier -t Type -n Replicas -r
-#
 # You will need python source for d1_common_python and d1_instance_generator to 
 # run this script. These can be retrieved from svn at:
 #   https://repository.dataone.org/software/cicore/trunk
@@ -10,13 +8,9 @@
 # D.V.
 #
 
-#The namespace for DataONE schema stuff
-NAMESPACE="http://ns.dataone.org/service/types/v1"
+VERSION="Version 0.0.4"
 
-#Script to urlencode, stdin to stdout
-URLENCODE="`dirname $0`/urlencode"
-
-#Base path to folder containing the pythin stuff
+#Base path to folder containing the python stuff
 WD="$HOME/Workspaces/DataONE_trunk/"
 export PYTHONPATH=".:$WD/d1_common_python/src:$WD/d1_instance_generator/src"
 
@@ -26,102 +20,147 @@ MYSUBJECT="$WD/d1_instance_generator/src/my_subject.py"
 #Script to generate system metadata
 GENSYS="$WD/d1_instance_generator/src/generate_sysmeta.py"
 
+#Location of XMLStarlet command
+XML="/usr/local/bin/xml"
+TMP="/tmp"
+
 #Destination of generated system metadata doc
-SYSDEST="/tmp/sysmeta.xml"
+sysmDest="${TMP}/sysmeta.$$.xml"
+baseurl=${NODE}
+raw=""
+verbose=""
+CMD=""
+certificate=""
+PID=""
+oType="application/octet-stream"
+nReplicas=3
+keepSysm=""
+
 
 usage()
 {
 cat << EOF
-usage: $0 -E Certificate -i PID [-t Type] [-n node] [-hrv] Object
 
-Create a new object on a node. Command will create system metadata, and call
-create() on the node specified in the NODE environment variable or from the
--n parameter.
+usage: $(basename $0) OPTIONS FILE
+
+Send FILE to a node. Command will create system metadata, and call create() on 
+the node with base URL specified in the NODE environment variable or from the 
+-b parameter.
 
 OPTIONS:
 
   -h  Show this message
   -E  Certificate to use for authentication
   -i  Identifier of the new object
-  -t  Object format identifier for new object
-  -n  Node to create the new object ($NODE)
-  -a  Number of replicas to request (3)
-  -s  Destination of generated system metadata ($SYSDEST)
+  -T  Object format identifier for new object
+  -b  Node to create the new object (${baseurl})
+  -a  Number of replicas to request (${nReplicas})
+  -Y  Destination of generated system metadata (${sysmDest})
+  -k  Keep system metadata (default = No)
   -r  Show raw response
   -v  Be a bit more verbose
+  -V  Show version (${VERSION})
+
 EOF
 }
 
-TARGET=$NODE
-RAW=""
-VERBOSE=""
-CMD=""
-CERTIFICATE=""
-PID=""
-OTYPE="application/octet-stream"
-NREPS=3
-while getopts "hvrn:E:i:a:t:s:" OPTION
+show_version()
+{
+  echo ${VERSION}
+}
+
+
+while getopts "hvVrkb:E:i:a:T:Y:" OPTION
 do
     case $OPTION in
-      h) usage; exit 1;;
-      n) TARGET=$OPTARG;;
-      v) VERBOSE=1;;
-      r) RAW=1;;
-      E) CERTIFICATE=$OPTARG;;
+      h) usage; exit 3;;
+      v) verbose=1;;
+      V) show_version; exit 3;;
+      r) raw=1;;
+      k) keepSysm=1;;
+      b) baseurl=$OPTARG;;
+      E) certificate=$OPTARG;;
       i) PID=$OPTARG;;
-      t) OTYPE=$OPTARG;;
-      a) NREPS=$OPTARG;;
-      s) SYSDEST=$OPTARG;;
-      \?) usage; exit 1;;
+      a) nReplicas=$OPTARG;;
+      T) oType=$OPTARG;;
+      Y) sysmDest=$OPTARG;;
+      \?) usage; exit 3;;
     esac
 done
 
-if [[ -z $TARGET ]]; then
-  echo "NODE or -n required"
-  exit 1
-fi
-if [[ -z $PID ]]; then
-  echo "Identifier is required"
-  exit 1
-fi
-if [[ -z $CERTIFICATE ]]; then
-  echo "Certificate is required"
-  exit 1
-fi
-if [[ -z $OTYPE ]]; then
-  echo "Object format identifier is required"
-  exit 1
-fi
-shift $(($OPTIND - 1))
-if [[ -z $1 ]]; then
-  echo "File for upload is required"
-  exit 1
-fi
-OBJECT=$1
-
-my_subject=$(python ${MYSUBJECT} -l 40 ${CERTIFICATE})
-if [[ $? -ne 0 ]]; then
-  echo "ERROR: certificate ${CERTIFICATE} has expired."
+if [[ -z ${baseurl} ]]; then
+  echo "NODE or -b required"
   exit 2
 fi
-if [[ -n $VERBOSE ]]; then
-  echo "SUBJECT =  $my_subject"
+if [[ -z ${PID} ]]; then
+  echo "Identifier is required"
+  exit 2
+fi
+if [[ -z ${certificate} ]]; then
+  echo "Certificate is required"
+  exit 2
+fi
+if [[ -z ${oType} ]]; then
+  echo "Object format identifier is required"
+  exit 2
+fi
+shift $(($OPTIND - 1))
+OBJECT=$1
+if [[ -z $OBJECT ]]; then
+  echo "File for upload is required"
+  exit 2
+fi
+
+my_subject=$(python ${MYSUBJECT} -l 40 ${certificate})
+if [[ $? -ne 0 ]]; then
+  echo "ERROR   : certificate ${certificate} has expired."
+  exit 2
+fi
+if [[ -n ${verbose} ]]; then
+  echo "SUBJECT : $my_subject"
 fi
 
 python ${GENSYS} -f "${OBJECT}" \
                  -i "${PID}" \
-                 -t "${OTYPE}" \
+                 -t "${oType}" \
                  -s "${my_subject}" \
-                 -n "${NREPS}" > ${SYSDEST}
+                 -n "${nReplicas}" > ${sysmDest}
 
-if [[ -n $VERBOSE ]]; then
-  echo "Generated system metadata is located at: ${SYSDEST}"
+if [[ -n ${verbose} ]]; then
+  echo "Generated system metadata is located at: ${sysmDest}"
 fi
 
-URL="${TARGET}/v1/object"
-CMD="curl -k -s -E  \"${CERTIFICATE}\" -X POST -F \"pid=${PID}\" -F \"object=@${OBJECT}\" -F \"sysmeta=@${SYSDEST}\" \"${URL}\" | xml fo"
+url="${baseurl}/v1/object"
+tmpfile="${TMP}/$(basename $0).$$.xml"
+
+CMD="curl -k -s -E  \"${certificate}\" -X POST -w \"%{http_code}\" \
+ -o \"${tmpfile}\" -F \"pid=${PID}\" -F \"object=@${OBJECT}\" \
+ -F \"sysmeta=@${sysmDest}\" \"${url}\""
 
 if [[ -n $VERBOSE ]]; then
   echo "Create Command = ${CMD}"
 fi
-eval $CMD
+
+status=$(eval ${CMD})
+
+if [[ ${status} == "200" ]]; then
+  if [[ -n ${verbose} ]]; then
+    echo "STATUS  : OK"
+  fi
+  if [[ -n ${raw} ]]; then
+    cat ${tmpfile}
+  else
+    xml fo ${tmpfile}
+  fi
+else
+  echo "ERROR   : Status of response = ${status}"
+  if [[ -n ${verbose} ]]; then
+    cat ${tmpfile}
+    echo
+  fi
+fi
+rm ${tmpfile}
+if [[ -z ${keepSysm} ]]; then
+  rm ${sysmDest}
+fi
+
diff --git a/d1formats b/d1formats
--- a/d1formats
+++ b/d1formats
@@ -1,5 +1,6 @@
 #!/bin/bash
-# Arguments -n Node -r -v
+# Arguments -b Node -T formatType -r -v
+#
 # Just lists the ObjectFormats that are registered on a node supporting the 
 # ListFormats method which is described over here:
 #   http://mule1.dataone.org/ArchitectureDocs-current/apis/CN_APIs.html
@@ -7,51 +8,94 @@
 # You'll be wanting to install xmlstarlet to run this. Actually just install it
 # anyway, it's good.
 #
+VERSION="Version 0.0.3"
 
+#Location of xmlstarlet command
+XML="/usr/local/bin/xml"
+TMP="/tmp"
+baseurl=$NODE
+formatType=""
 
-target=$NODE
 
 usage()
 {
 cat << EOF
-usage: $0 [-r] [-n node]
+
+usage: $(basename $0) OPTIONS
 
 List the object formats available on a (Coordinating) Node specified by the NODE
-environment variable or from the -n parameter.
+environment variable or from the -b parameter.
 
 OPTIONS:
 
   -h  Show this message
-  -n  Node to create the new object ($NODE)
+  -b  Base URL of node being contacted to read format list ($NODE)
+  -T  Show only formatType specified (METADATA, DATA, RESOURCE)
   -r  Show raw response
   -v  Be a bit more verbose
+ 
 EOF
 }
 
+show_version()
+{
+  echo ${VERSION}
+}
 
-while getopts "hvrn:" OPTION
+
+
+## Parse command line
+while getopts "hvVrb:T:" OPTION
 do
     case $OPTION in
       h) usage; exit 1;;
-      n) target=$OPTARG;;
+      b) baseurl=$OPTARG;;
+      T) formatType=$OPTARG;;
       v) verbose=1;;
       r) raw=1;;
+      V) show_version exit 1;;
       \?) usage; exit 1;;
     esac
 done
 
 
-url="${target}/v1/formats"
+
+
+## REST endpoint URL relative to base url
+url="${baseurl}/v1/formats"
+
 if [[ -n ${verbose} ]]; then
   echo "URL     : ${url}"
 fi
 
-if [[ -n ${raw} ]]; then
-  CMD="curl -k -s \"${url}\" | xml fo"
-else
-  CMD="curl -k -s \"${url}\" | xml sel -t -m \"//objectFormat\" -v \"formatId\" -n"
-fi
+## Save response to a temp file, capture HTTP status
+tmpfile="${TMP}/$(basename $0).$$.xml"
+CMD="curl -k -s -w \"%{http_code}\" -o \"${tmpfile}\" \"${url}\""
 if [[ -n ${verbose} ]]; then
   echo "Command : ${CMD}"
+  echo
 fi
-eval ${CMD}
+
+status=$(eval ${CMD})
+
+if [[ ${status} == "200" ]]; then
+  if [[ -n ${raw} ]]; then
+    xml fo ${tmpfile}
+  else
+    if [[ -z ${formatType} ]]; then
+      ${XML} sel -t -m "//objectFormat" \
+                 -v "substring(concat(formatType,'          '),1,10)" \
+                 -v "formatId" -n ${tmpfile}
+    else
+      ${XML} sel -t -m "//objectFormat[formatType='${formatType}']" \
+                 -v "substring(concat(formatType,'          '),1,10)" \
+                 -v "formatId" -n ${tmpfile}
+    fi
+  fi
+else
+  echo "ERROR   : Status of response = ${status}"
+  if [[ -n ${verbose} ]]; then
+    cat ${tmpfile}
+  fi
+fi
+rm ${tmpfile}
diff --git a/d1ping b/d1ping
--- a/d1ping
+++ b/d1ping
@@ -1,13 +1,13 @@
 #!/bin/bash
-# Arguments -n Node
 #
 # Ping a DataONE node, returning the time taken for operation.
-# Exit code and parameters can conform to nagios plugin expectations
+# Exit code and parameters can conform to nagios3 plugin expectations
 
-VERSION="Version 0.0.2"
+VERSION="Version 0.0.3"
 CURL="/usr/bin/curl -k -s -o /dev/null"
 
-target=$NODE
+HTTP="https"
+baseurl=$NODE
 verbose=""
 raw=""
 nagios=""
@@ -20,7 +20,7 @@ usage()
 {
 cat << EOF
 
-`basename $0` [-r] [-v] [-w warning] [-c critical] [-V] [-n node]
+$(basename $0) OPTIONS
 
 Ping the DataONE node specified by the NODE environment variable or from the -n
 parameter. This script can be used as a Nagios plugin for a basic check of node
@@ -29,14 +29,15 @@ availablility. To do so, just call with -n and optionally -c and -w.
 OPTIONS:
 
   -h  Show this message
-  -n  Node to create the new object ($NODE)
+  -b  Node to create the new object ($NODE)
   -r  Show raw response
   -v  Be a bit more verbose
   -V  Show version (${VERSION})
   -w  Warning threshold (ping time in seconds, ${warning})
   -c  Critical threshold (ping time in seconds, ${critical})
-  -H  Host name, must set -T node type when used
-  -T  Node type, one of "CN", "GMN", "METACAT"
+  -H  Host name, must set -P node type when used
+  -P  Base path for node, e.g. "/knb/d1/mn", "/mn", or "/cn"
+  -T  Don't use SSL (i.e. http rather than https)
 
 EOF
 }
@@ -47,44 +48,39 @@ show_version()
 }
 
 ## Parse the command line
-while getopts "hvVrn:w:c:H:T:" OPTION
+while getopts "hvVrTb:w:c:H:P:" OPTION
 do
     case $OPTION in
       h) usage; exit 1;;
-      n) target=$OPTARG;;
+      b) baseurl=$OPTARG;;
       v) verbose=1;;
       r) raw=1;;
       w) warning=$OPTARG;;
       c) critical=$OPTARG;;
       V) show_version;;
       H) host=$OPTARG;;
-      T) ntype=$OPTARG;;
+      P) basePath=$OPTARG;;
+      T) HTTP="http";;
       \?) usage; exit 1;;
     esac
 done
 
-## Hack alert - should really be setting the base path for the node as a 
-## command line param.
+# Set baseurl if host and base path provided
 if [[ -n ${host} ]]; then
-  if [[ -z ${ntype} ]]; then
-    echo "-T node type required with -H host"
-    echo "Node types = CN, GMN, METACAT"
+  if [[ -z ${basePath} ]]; then
+    echo "-P base path required with -H host"
     exit 3
   fi
-  if [[ "${ntype}"=="CN" ]]; then
-    target="https://${host}/cn"
-  elif [[ "${ntype}"=="GMN" ]]; then
-    target="https://${host}/mn"
-  elif [[ "${ntype}"=="METACAT" ]]; then
-    target="https://${host}/knb/d1/mn"
-  else
-    echo "Unknown node type: ${ntype}"
-    exit 3
-  fi
+  baseurl="${HTTP}://${host}${basePath}"
+fi
+
+if [[ -z ${baseurl} ]]; then
+  echo "NODE, -b, or -H and -P required"
+  exit 1
 fi
 
 ## Ping API REST endpoint
-url="${target}/v1/monitor/ping"
+url="${baseurl}/v1/monitor/ping"
 if [[ -n ${verbose} ]]; then
   echo "URL     : ${url}"
 fi
@@ -112,16 +108,14 @@ TIMEFORMAT=$SAVET
 if [[ -n ${verbose} ]]; then
   echo "Result  : ${res[0]}, ${res[1]}"
   exit 3
-else
-  EC=2
-  echo ${res[1]}
-  if [[ "${res[0]}"=="200" ]]; then
-    EC=1
-    if [[ ${res[1]} < ${warning} ]]; then
-      EC=0
-    elif [[ ${res[1]} > ${critical} ]]; then
-      EC=2
-    fi
+EC=2
+echo ${res[1]}
+if [[ "${res[0]}"=="200" ]]; then
+  EC=1
+  if [[ ${res[1]} < ${warning} ]]; then
+    EC=0
+  elif [[ ${res[1]} > ${critical} ]]; then
+    EC=2
   fi
-  exit $EC
 fi
+exit ${EC}
