Fix the order of the get opts, and how colons are used in the options parsing.

diff --git a/d1noderegister b/d1noderegister
--- a/d1noderegister
+++ b/d1noderegister
@@ -10,8 +10,8 @@ XML="/usr/local/bin/xml"
 TMP="/tmp"
 baseurl=$NODE
 tmpfile="${TMP}/$(basename $0).$$.xml"
-nodefile="./node.xml"
-clientfile="./client.pem"
+nodefile=
+clientfile=
 keepresp=""
 
 usage()
@@ -27,9 +27,8 @@ OPTIONS:
 
   -h  Show this message
   -b  Base URL of Coordinating Node being contacted to register the MN (${baseurl})
-  -f  The path to the MN node XML file (default ./node.xml)
-  -E  The path to the MN client SSL certificate PEM (default ./client.pem)
-  -k  Keep response (default is to delete on exit)
+  -f  The path to the MN node XML file
+  -E  The path to the MN client SSL certificate PEM (concatenated cert and key)
   -D  Destination for response (${tmpfile})
   -r  Show raw response
   -v  Be a bit more verbose
@@ -40,46 +39,51 @@ EOF
 
 show_version()
 {
-  echo ${VERSION}
+    echo ${VERSION}
 }
 
 
 ## Parse command line
-while getopts "hvVrkfEb:D:" OPTION
+while getopts ":hvVrf:E:b:D:" OPTION
 do
     case $OPTION in
       h) usage; exit 1;;
       b) baseurl=$OPTARG;;
       f) nodefile=$OPTARG;;
       E) clientfile=$OPTARG;;
-      k) keepresp=1;;
       D) tmpfile=$OPTARG;;
       v) verbose=1;;
       r) raw=1;;
       V) show_version; exit 1;;
-      \?) usage; exit 1;;
+      \?) echo "ERROR:   Invalid option: -$OPTARG";usage; exit 1;;
     esac
 done
 
 if [[ -z ${baseurl} ]]; then
-  echo "ERROR   : A CN Base URL must be provided by -b or the NODE environment variable"
-  echo
-  echo "DataONE environments and base URLs include:"
-  echo -e "DEVELOPMENT:\thttps://cn-dev.test.dataone.org/cn"
-  echo -e "SANDBOX    :\thttps://cn-sandbox.test.dataone.org/cn"
-  echo -e "STAGING    :\thttps://cn-stage.test.dataone.org/cn"
-  echo -e "PRODUCTION :\thttps://cn.dataone.org/cn"
-  exit 1
- fi
+    echo "ERROR   : A CN Base URL must be provided by -b or the NODE environment variable"
+    echo
+    echo "DataONE environments and base URLs include:"
+    echo -e "DEVELOPMENT:\thttps://cn-dev.test.dataone.org/cn"
+    echo -e "SANDBOX    :\thttps://cn-sandbox.test.dataone.org/cn"
+    echo -e "STAGING    :\thttps://cn-stage.test.dataone.org/cn"
+    echo -e "PRODUCTION :\thttps://cn.dataone.org/cn"
+    echo
+    usage
+    exit 1
+fi
 
 if [[ ! -r ${nodefile} ]]; then
-    echo "ERROR   : A node XML file must be provided by with the -f option"
-  exit 1
+    echo "ERROR   : A node XML file must be provided with the -f option"
+    echo
+    usage
+    exit 1
 fi
 
 if [[ ! -r ${clientfile} ]]; then
-    echo "ERROR   : A client SSL certificate file must be provided by with the -E option"
-  exit 1
+    echo "ERROR   : A client SSL certificate file must be provided with the -E option"
+    echo
+    usage
+    exit 1
 fi
 
 private_count=$(grep "PRIVATE" ${clientfile} | wc -l);
@@ -87,13 +91,17 @@ cert_count=$(grep "CERTIFICATE" ${clientfile} | wc -l);
 
 if [[ ! $private_count -eq 2 ]]; then
     echo "ERROR   : The file ${clientfile} does not contain a 'CERTIFICATE' section."
-    echo "          Please concatenate the MN client SSL certificate and key into this file"
+    echo "          Please concatenate the MN client SSL certificate and key into this file."
+    echo
+    usage
     exit 1
 fi
 
-if [[ ! $private_count -eq 2 ]]; then
-    echo "ERROR   : The file ${clientfile} does not contain a 'PRIVATE KEY'."
-    echo "          Please concatenate the MN client SSL certificate and key into this file"
+if [[ ! $cert_count -eq 2 ]]; then
+    echo "ERROR   : The file ${clientfile} does not contain a 'PRIVATE KEY' section."
+    echo "          Please concatenate the MN client SSL certificate and key into this file."
+    echo
+    usage
     exit 1
 fi
 
@@ -101,34 +109,36 @@ fi
 url="${baseurl}/v1/node"
 
 if [[ -n ${verbose} ]]; then
-  echo "URL     : ${url}"
+    echo "URL     : ${url}"
 fi
 
 ## Save response to temp file, capture HTTP status
-CMD="curl -X POST -E ${clientfile} -k -s -w \
-    \"%{http_code}\" -o \"${tmpfile}\" -f \"node=@${nodefile}\" \
-    \"${url}\""
+CMD="curl -X POST \
+ -E ${clientfile} -k -s \
+ -o ${tmpfile} \
+ -w \"%{http_code}\" \
+ -F \"node=@${nodefile}\" \
+ \"${url}\""
+
 if [[ -n ${verbose} ]]; then
-  echo "Command : ${CMD}"
-  echo
+    echo "Command : ${CMD}"
+    echo
 fi
 
 status=$(eval ${CMD})
 
 EC=0
-if [[ ${status} == "200" ]]; then
-  if [[ -n ${raw} ]]; then
-    echo ${tmpfile}
-  fi
+if [[ ${status} -eq 200 ]]; then
+    echo Success.
+    if [[ ${raw} -eq 1 ]]; then
+      cat ${tmpfile}
+    fi
 else
-  EC=1
-  echo "ERROR   : Status of response = ${status}"
-  if [[ -n ${verbose} ]]; then
-    cat ${tmpfile}
-  fi
-fi
-if [[ -z ${keepresp} ]]; then
-  rm ${tmpfile}
+    EC=1
+    echo "ERROR   : Status of response = ${status}"
+    if [[ -n ${verbose} ]]; then
+      cat ${tmpfile}
+    fi
 fi
 exit $EC
 
